name: tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        r-version: ['4.4', '4.3', 'devel']
        exclude:
          - os: windows-latest
            r-version: 'devel' # R devel is unstable on Windows
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
      - name: Set up dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install libgit2 -y
          choco install rtools -y
          refreshenv
      - name: Install dependencies
        run: |
          install.packages('devtools')
          install.packages('testthat')
          devtools::install_deps(dependencies = TRUE)
      - name: Run tests
        run: |
          devtools::test()
